### ISSUE TITLE
Error when change AD password contain special characters

### ISSUE THREAD

**Issue by chienbinhso13** [jirutka/ldap-passwd-webui#9]
When I try new pass as:"O3D0eHAcuzia2rX$G"
> 127.0.0.1 - - [17/Jul/2017 15:53:50] "GET / HTTP/1.1" 200 1350
> 2017-07-17 15:54:10,253 WARNING: Unsuccessful attemp to change password for test: 0000052d: atrerr: dsid-03191083, #1:
> 	0: 0000052d: dsid-03191083, problem 1005 (constraint_att_type), data 0, att 9005a (unicodepwd)

I've try 

> new_pass = base64.b64encode(bytes(new_pass, 'utf-16le'))

but it's the same as none

**Comment by jirutka** [comment]
Have you figured out where was the problem?

**Comment by chienbinhso13** [comment]
If the user is locked, disable, or password expired, the problem will show.
I'm using c.modify(user_dn,{LDAP_MODIFY("userAccountControl ",512)}) to fix this error.
